# 기업용 AI 가드레일 시스템 설정
# 비민감 정보만 포함 (민감 정보는 .env 파일 또는 Azure App Settings 사용)

# Azure OpenAI 모델 배포 이름
azure_openai_chat_deployment_name: "GPT-4.1"
azure_openai_embedding_deployment_name: "text-embedding-3-small"
azure_openai_api_version: "2024-12-01-preview"

# Azure AI Search 설정
azure_search_index_name: "bank-financial-policy-index-2"
azure_skillset_name: "bank-financial-policy-skillset"
azure_skillset_definition_path: "config/skillset_definition.json" # 스킬셋 JSON 정의 파일 경로

# Azure Blob Storage 설정 (RAG 소스 파일용)
blob_storage_container_name: "container"
rag_source_directory: "RAG_source"
blob_storage_policy_path: "policy"  # Blob 내 정책 파일 경로

# 동적 버퍼 설정
initial_buffer_size: 50
subsequent_buffer_size: 200

# LLM 설정
llm_temperature: 0  # 일관성 있는 판단을 위해 0으로 설정
llm_max_retries: 3
llm_timeout: 30
